# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23d1f0cb58ef61b28329c93323213d44f81de05082953b390ffe7b38dc7413491e3dcef294e0547956db5d8c0a071fd47e334ed977ee7e0d5433e899e0e969d2

test:
  secret_key_base: b427179aafa3708d67652f701165c8bc590ea4d6d8127ae078e86419f74c15ec3e7443972271b4798f29b9a85bcb1b415a00f71d101e975f404b179722b128dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
